import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "@/actions/getCurrentUser";
import { Toaster } from "react-hot-toast";
import NavBar from "./components/nav/NavBar";
import { PrimeReactProvider } from "primereact/api";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Contacts App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          toastOptions={{
            style: {
              background: "rgb(51 65 85)",
              color: "#fff",
            },
          }}
        />
        <div className="flex flex-col min-h-screen  ">
          <NavBar currentUser={currentUser} />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
